### ISSUE TITLE
Suggestion : Change title color

### ISSUE THREAD

**Issue by oproiuraulgrigore** [oproiuraulgrigore/GitHub-crash-course#1]
Maybe the the main title color can be a little bit orange.

The styling rule could be changed like this : 

```css
h1 {
  color: #efa82e;
}
```
